[package]
name = "artefac-sim-client"
version = "0.1.0"
description = "Artefac Simulation Client"
authors = ["Evolutek"]
edition = "2021"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["devtools"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
