# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='realtime.proto',
  package='realtime',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0frealtime.proto\x12\x08realtime\x22.\n\x10SubscribeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0bfilter_type\x18\x02 \x01(\t\x22.\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x13\n\x0cpayload_json\x18\x02 \x01(\t2H\n\x08Realtime\x12<\n\x0cStreamEvents\x12\x1a.realtime.SubscribeRequest\x1a\x0f.realtime.Event0\x01b\x06proto3')
)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='realtime.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='realtime.SubscribeRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter_type', full_name='realtime.SubscribeRequest.filter_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=29,
  serialized_end=75,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='realtime.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='realtime.Event.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload_json', full_name='realtime.Event.payload_json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=77,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'realtime_pb2'
  # @@protoc_insertion_point(class_scope:realtime.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'realtime_pb2'
  # @@protoc_insertion_point(class_scope:realtime.Event)
  })
_sym_db.RegisterMessage(Event)


# @@protoc_insertion_point(module_scope)

