# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from . import realtime_pb2 as realtime__pb2


class RealtimeStub(object):
    """Realtime streaming of backend events"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.unary_stream(
            '/realtime.Realtime/StreamEvents',
            request_serializer=realtime__pb2.SubscribeRequest.SerializeToString,
            response_deserializer=realtime__pb2.Event.FromString,
        )


class RealtimeServicer(object):
    """Realtime streaming of backend events"""

    async def StreamEvents(self, request, context):
        """Server-to-client streaming of events"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RealtimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'StreamEvents': grpc.unary_stream_rpc_method_handler(
            servicer.StreamEvents,
            request_deserializer=realtime__pb2.SubscribeRequest.FromString,
            response_serializer=realtime__pb2.Event.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'realtime.Realtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

